name: Deploy website

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  production-deploy:
    permissions:
      actions: read
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/studio-production-deploy.yml
    secrets:
      DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
